// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/xm-chentl/goframedemo/internal/logic/person"
	_ "github.com/xm-chentl/goframedemo/internal/logic/user_app"
	_ "github.com/xm-chentl/goframedemo/internal/logic/user_buy_history"
)
