// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Person is the golang structure of table person for DAO operations like Where/Data.
type Person struct {
	g.Meta    `orm:"table:person, do:true"`
	Id        interface{} // 标识
	Name      interface{} // 名称
	Age       interface{} // 年龄
	Status    interface{} // 状态
	CreatedAt *gtime.Time // 创建时间
}
