// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserBuyHistory is the golang structure of table user_buy_history for DAO operations like Where/Data.
type UserBuyHistory struct {
	g.Meta  `orm:"table:user_buy_history, do:true"`
	Id      interface{} //
	UserId  interface{} // 用户标识
	AppId   interface{} // 应用标识
	AppName interface{} // 应用名称
	BuyTime *gtime.Time // 购买时间
	Status  interface{} // 订单状态#1:已付款
}
