
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
    - link:     "mysql:root:123456@tcp(localhost:3308)/mytest"
      jsonCase: "Snake"
