// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/xm-chentl/goframedemo/internal/model/entity"
	userApp "github.com/xm-chentl/goframedemo/internal/model/views/user_app"
)

type (
	IUserApp interface {
		Get(ctx context.Context, id int) (entry entity.UserApp, err error)
		Insert(ctx context.Context, req userApp.BuyAppReq) (id int64, err error)
		UpdateLicense(ctx context.Context, req userApp.LicenseAppGenReq) (err error)
	}
)

var (
	localUserApp IUserApp
)

func UserApp() IUserApp {
	if localUserApp == nil {
		panic("implement not found for interface IUserApp, forgot register?")
	}
	return localUserApp
}

func RegisterUserApp(i IUserApp) {
	localUserApp = i
}
