// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/xm-chentl/goframedemo/internal/dao/internal"
)

// internalUserBuyHistoryDao is internal type for wrapping internal DAO implements.
type internalUserBuyHistoryDao = *internal.UserBuyHistoryDao

// userBuyHistoryDao is the data access object for table user_buy_history.
// You can define custom methods on it to extend its functionality as you wish.
type userBuyHistoryDao struct {
	internalUserBuyHistoryDao
}

var (
	// UserBuyHistory is globally public accessible object for table user_buy_history operations.
	UserBuyHistory = userBuyHistoryDao{
		internal.NewUserBuyHistoryDao(),
	}
)

// Fill with you ideas below.
