// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Person is the golang structure for table person.
type Person struct {
	Id        int         `json:"id"         ` // 标识
	Name      string      `json:"name"       ` // 名称
	Age       int         `json:"age"        ` // 年龄
	Status    int         `json:"status"     ` // 状态
	CreatedAt *gtime.Time `json:"created_at" ` // 创建时间
}
