// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserBuyHistory is the golang structure for table user_buy_history.
type UserBuyHistory struct {
	Id      int         `json:"id"       ` //
	UserId  int         `json:"user_id"  ` // 用户标识
	AppId   int         `json:"app_id"   ` // 应用标识
	AppName string      `json:"app_name" ` // 应用名称
	BuyTime *gtime.Time `json:"buy_time" ` // 购买时间
	Status  int         `json:"status"   ` // 订单状态#1:已付款
}
